server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=5s ipv6=off;

    set $dashboard http://dashboard:80;
    set $ingest    http://ingest-api:5000;
    set $query     http://query-api:5001;

    location / {
        proxy_pass $dashboard;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /ingest/ {
        proxy_pass $ingest;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /query/ {
        proxy_pass $query;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /nginx-health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
