resolver 127.0.0.11 valid=5s ipv6=off;

server {
    listen 80;
    server_name _;

    location /ingest/ {
        set $upstream_ingest ingest-api:5000;
        proxy_pass         http://$upstream_ingest;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }

    location /query/ {
        set $upstream_query query-api:5001;
        proxy_pass         http://$upstream_query;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }

    location / {
        set $upstream_dash dashboard:80;
        proxy_pass       http://$upstream_dash;
        proxy_set_header Host $host;
    }
}
