services:
  servidor1:
    build:
      context: .
      dockerfile: Dockerfile_server1.sshd
      network: host
    container_name: servidor1
    hostname: servidor1
    ports:
      - "2224:22"
    networks:
       - app-net
    privileged: true 

  servidor2:
    build:
      context: .
      dockerfile: Dockerfile_server2.sshd
      network: host
    container_name: servidor2
    hostname: servidor2
    ports:
      - "2223:23"
    networks:
       - app-net
    privileged: true
  
  jumphost:
    build:
      context: .
      dockerfile: Dockerfile_jumphost.sshd
      network: host
    container_name: jumphost
    hostname: jumphost
    ports:
      - "2222:24"
    networks:
       - app-net
    privileged: true

networks:
  app-net:
    driver: bridge 

