services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      network: host
    image: dashboard:latest
    hostname: dashboard
    ports:
      - "8080:80"
    networks:
      - frontend-net                    
    deploy:
      mode: replicated               
      replicas: 3
      update_config:
        parallelism: 1               
        delay: 10s                   
        failure_action: rollback    
        order: start-first          
      restart_policy:
        condition: on-failure 
  
  aggregator:
    build:
      context: ./aggregator
      dockerfile: Dockerfile
      network: host
    image: aggregator:latest  
    hostname: aggregator
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=db_name
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - backend-net                     
    deploy:
      mode: global               
      update_config:
        parallelism: 1               
        delay: 10s                   
        failure_action: rollback    
        order: start-first          
      restart_policy:
        condition: on-failure 
  
  alerter:
    build:
      context: ./alerter
      dockerfile: Dockerfile
      network: host
    hostname: alerter
    image: alerter:latest
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=db_name
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - backend-net
    secrets:
      - db_pass                      
    deploy:
      mode: global               
      update_config:
        parallelism: 1               
        delay: 10s                   
        failure_action: rollback    
        order: start-first          
      restart_policy:
        condition: on-failure 
  
  ingest-api:
    build:
      context: ./ingest-api
      dockerfile: Dockerfile
      network: host
    hostname: ingest-api
    image: ingest-api:latest
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=db_name
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "5000:5000"
    networks:
      - frontend-net
      - backend-net                    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      mode: replicated               
      replicas: 4 
      update_config:
        parallelism: 1               
        delay: 10s                   
        failure_action: rollback    
        order: start-first          
      restart_policy:
        condition: on-failure
  
  query-api:
    build:
      context: ./query-api
      dockerfile: Dockerfile
      network: host
    hostname: query-api
    image: query-api:latest
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=db_name
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "5001:5001"
    networks:
      - frontend-net
      - backend-net                    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      mode: replicated               
      replicas: 2
      update_config:
        parallelism: 1               
        delay: 10s                   
        failure_action: rollback    
        order: start-first          
      restart_policy:
        condition: on-failure
  
  redis:
    image: redis:alpine
    networks:
      - backend-net
    secrets:
      - db_pass                      
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      mode: replicated               
      replicas: 1
      update_config:
        parallelism: 1               
        delay: 10s                   
        failure_action: rollback    
        order: start-first          
      restart_policy:
        condition: on-failure
  
  postgres:
    image: postgres:17-alpine
    environment:
    - POSTGRES_USER=db_user
    - POSTGRES_PASSWORD=db_pass
    - POSTGRES_DB=db_name
    - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - backend-net
    secrets:
      - db_pass
      - db_name
      - db_user
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      mode: replicated               
      replicas: 1
      placement:
        constraints:
          - node.label.role == db  
      update_config:
        parallelism: 1               
        delay: 10s                   
        failure_action: rollback    
        order: start-first          
      restart_policy:
        condition: on-failure

networks:
  frontend-net:
    driver: overlay  
    attachable: true
  backend-net:
    driver: overlay
    attachable: true

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_pass:
    file: ./secrets/db_pass.txt